name: Update Index

on:
  push:
    branches: [main]
    paths: ["Library/**"]

permissions:
  contents: write

jobs:
  update:
    name: 'Update Index'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: List Libraries
        shell: pwsh
        run: |
          $ignore = @()
          if (Test-Path "ignore.txt") {
            $ignore = Get-Content "ignore.txt"
          }

          # Get all files under Library and remove the path up to Library
          $allItems = Get-ChildItem -File -Recurse ./Library/
          $allItems = $allItems.FullName.Substring($(Get-Location).Path.Length + 1)

          $index = $allItems | ? { $_ -notin $ignore } | % { @{ name = $_ } } | ConvertTo-Json
          Write-Host $index
          Set-Content "index.json" $index

      - name: Check if index has changed
        shell: pwsh
        id: check_index
        run: |
          $diff = git diff --name-only
          $SourceDiff = $diff | Where-Object { $_ -eq "index.json" }
          $HasDiff = $SourceDiff.Length -gt 0

          Add-Content -Path $env:GITHUB_OUTPUT -Value "has_changed=$HasDiff"

          Write-Host "Index has changed? $HasDiff"

      - name: Commit and push if on main
        if: steps.check_index.outputs.has_changed == 'True'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.json || true
          git commit -m "Auto-generated index.json [skip ci]" || true

      - name: Push changes with Git CLI
        if: steps.check_index.outputs.has_changed == 'True'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:main

